### ISSUE TITLE
有疑问~请大神解答

### ISSUE THREAD

**Issue by 0704681032** [manxisuo/ZhihuMagnifier#1]
1.  if (-1 === ts || ts - ts0 >= 500)
   
   这里为什么是ts === -1 ?

2.去掉下面一段有什么影响了？
(function() {
    var ts0 = -1;
    $('#js-home-feed-list').on('DOMNodeInserted', function(){
        var ts = new Date().getTime();

```
    // 防止一次插入多个节点时触发多次注册动作
    if (-1 === ts || ts - ts0 >= 500) {      
        setTimeout(avatarHoverHandler); // 加入到事件队列的末尾
    }

    ts0 = ts;
});
```

})();

下面不是已经有手动执行？求大大解答
// 首次载入脚本时触发一次avatarHoverHandler
avatarHoverHandler();

**Comment by manxisuo** [comment]
“大神”不敢当。
**1. 这个地方是我写错了，应该是：**
`if (-1 === ts0 || ts - ts0 >= 500)`
或者直接
`if (ts - ts0 >= 500)`
-1是表示“很久以前”的时间戳，不一定是-1，只要是取一个比较小的值就可以了。
**2. 这个地方是针对知乎首页动态加载的：**
当你打开知乎首页时，只加载一部分动态消息，当滚动到页面底部时会加载更多消息，很多网站都是这样的。
代码最后一行：
`avatarHoverHandler();`
只是在首次载入页面时将监听函数注册到开始的那些头像(的mouseover)上，后来动态载入的那些头像是要重新注册的。而每次插入新动态时，会发生DOMNodeInserted事件，所以就选择了在此事件发生时进行注册。

**Comment by 0704681032** [comment]
非常感谢,非常详尽的解答！

**Comment by manxisuo** [comment]
可以看一下最新的代码，已经去除了DOMNodeInserted，用了更简洁的方式。

**Comment by 0704681032** [comment]
:+1:  事件代理！
